INSERT INTO item_catalog.currency (code, rate) VALUES ('FJD', 2.4193);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MXN', 21.2316);
INSERT INTO item_catalog.currency (code, rate) VALUES ('STD', 23828.2486);
INSERT INTO item_catalog.currency (code, rate) VALUES ('LVL', 0.6847);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SCR', 15.5241);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CDF', 1851.8723);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BBD', 2.2531);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GTQ', 8.6405);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CLP', 748.3373);
INSERT INTO item_catalog.currency (code, rate) VALUES ('HNL', 27.6530);
INSERT INTO item_catalog.currency (code, rate) VALUES ('UGX', 4231.0637);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ZAR', 15.7967);
INSERT INTO item_catalog.currency (code, rate) VALUES ('TND', 3.4100);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CUC', 1.1320);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BSD', 1.1313);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SLL', 9847.9746);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SDG', 53.8611);
INSERT INTO item_catalog.currency (code, rate) VALUES ('IQD', 1349.8516);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CUP', 29.9967);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GMD', 56.0260);
INSERT INTO item_catalog.currency (code, rate) VALUES ('TWD', 34.9151);
INSERT INTO item_catalog.currency (code, rate) VALUES ('RSD', 117.9724);
INSERT INTO item_catalog.currency (code, rate) VALUES ('DOP', 57.1709);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KMF', 492.8232);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MYR', 4.6574);
INSERT INTO item_catalog.currency (code, rate) VALUES ('FKP', 0.8673);
INSERT INTO item_catalog.currency (code, rate) VALUES ('XOF', 655.9697);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GEL', 3.0507);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BTC', 0.0002);
INSERT INTO item_catalog.currency (code, rate) VALUES ('UYU', 38.3687);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MAD', 10.8540);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CVE', 110.2702);
INSERT INTO item_catalog.currency (code, rate) VALUES ('TOP', 2.5666);
INSERT INTO item_catalog.currency (code, rate) VALUES ('AZN', 1.9300);
INSERT INTO item_catalog.currency (code, rate) VALUES ('OMR', 0.4350);
INSERT INTO item_catalog.currency (code, rate) VALUES ('PGK', 3.8252);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KES', 114.3275);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SEK', 10.4924);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BTN', 78.3712);
INSERT INTO item_catalog.currency (code, rate) VALUES ('UAH', 30.2379);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GNF', 10329.0538);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ERN', 16.9797);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MZN', 72.7283);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SVC', 9.9000);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ARS', 47.6473);
INSERT INTO item_catalog.currency (code, rate) VALUES ('QAR', 4.1217);
INSERT INTO item_catalog.currency (code, rate) VALUES ('IRR', 47660.7999);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MRO', 404.1069);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CNY', 7.5888);
INSERT INTO item_catalog.currency (code, rate) VALUES ('THB', 35.8874);
INSERT INTO item_catalog.currency (code, rate) VALUES ('UZS', 9558.4253);
INSERT INTO item_catalog.currency (code, rate) VALUES ('XPF', 119.2628);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BDT', 95.1383);
INSERT INTO item_catalog.currency (code, rate) VALUES ('LYD', 1.5732);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BMD', 1.1320);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KWD', 0.3443);
INSERT INTO item_catalog.currency (code, rate) VALUES ('PHP', 58.4868);
INSERT INTO item_catalog.currency (code, rate) VALUES ('RUB', 72.8075);
INSERT INTO item_catalog.currency (code, rate) VALUES ('PYG', 7027.2092);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ISK', 135.3857);
INSERT INTO item_catalog.currency (code, rate) VALUES ('JMD', 146.0900);
INSERT INTO item_catalog.currency (code, rate) VALUES ('COP', 3530.2724);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MKD', 61.4180);
INSERT INTO item_catalog.currency (code, rate) VALUES ('USD', 1.1320);
INSERT INTO item_catalog.currency (code, rate) VALUES ('DZD', 134.6800);
INSERT INTO item_catalog.currency (code, rate) VALUES ('PAB', 1.1314);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GGP', 0.8657);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SGD', 1.5314);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ETB', 32.4570);
INSERT INTO item_catalog.currency (code, rate) VALUES ('JEP', 0.8657);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KGS', 79.0589);
INSERT INTO item_catalog.currency (code, rate) VALUES ('SOS', 656.5320);
INSERT INTO item_catalog.currency (code, rate) VALUES ('VEF', 11.3054);
INSERT INTO item_catalog.currency (code, rate) VALUES ('VUV', 126.7785);
INSERT INTO item_catalog.currency (code, rate) VALUES ('LAK', 9787.1323);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BND', 1.5321);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ZMK', 10188.9220);
INSERT INTO item_catalog.currency (code, rate) VALUES ('XAF', 655.9697);
INSERT INTO item_catalog.currency (code, rate) VALUES ('LRD', 186.4894);
INSERT INTO item_catalog.currency (code, rate) VALUES ('XAG', 0.0755);
INSERT INTO item_catalog.currency (code, rate) VALUES ('CHF', 1.1343);
INSERT INTO item_catalog.currency (code, rate) VALUES ('HRK', 7.4344);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ALL', 123.4624);
INSERT INTO item_catalog.currency (code, rate) VALUES ('DJF', 201.1708);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ZMW', 14.1585);
INSERT INTO item_catalog.currency (code, rate) VALUES ('TZS', 2620.9236);
INSERT INTO item_catalog.currency (code, rate) VALUES ('VND', 26246.0399);
INSERT INTO item_catalog.currency (code, rate) VALUES ('XAU', 0.0009);
INSERT INTO item_catalog.currency (code, rate) VALUES ('AUD', 1.5789);
INSERT INTO item_catalog.currency (code, rate) VALUES ('ILS', 4.0349);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GHS', 5.9111);
INSERT INTO item_catalog.currency (code, rate) VALUES ('GYD', 236.7646);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KPW', 1018.8493);
INSERT INTO item_catalog.currency (code, rate) VALUES ('BOB', 7.8174);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KHR', 4571.7810);
INSERT INTO item_catalog.currency (code, rate) VALUES ('MDL', 19.9960);
INSERT INTO item_catalog.currency (code, rate) VALUES ('IDR', 15952.5863);
INSERT INTO item_catalog.currency (code, rate) VALUES ('KYD', 0.9428);
INSERT INTO item_catalog.currency (code, rate) VALUES ('AMD', 549.4774);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BWP', 11.9591);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'SHP', 1.4952);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'TRY', 6.5376);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'LBP', 1706.0205);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'TJS', 10.6680);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'JOD', 0.8020);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'AED', 4.1578);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'HKD', 8.8778);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'RWF', 1023.1026);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'EUR', 1.0000);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'LSL', 15.7798);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'DKK', 7.4781);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'CAD', 1.5095);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BGN', 1.9558);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MMK', 1716.2080);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MUR', 39.3961);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'NOK', 9.6094);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'SYP', 582.9552);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'IMP', 0.8657);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'ZWL', 364.8901);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'GIP', 0.8653);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'RON', 4.7665);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'LKR', 197.5312);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'NGN', 407.5028);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'CRC', 680.7724);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'CZK', 25.6598);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'PKR', 160.2787);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'XCD', 3.0592);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'ANG', 2.1099);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'HTG', 95.8666);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BHD', 0.4260);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'KZT', 429.3155);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'SRD', 8.4421);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'SZL', 15.8025);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'LTL', 3.3424);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'SAR', 4.2375);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'TTD', 7.6602);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'YER', 283.3844);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MVR', 17.4363);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'AFN', 87.6804);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'INR', 78.2982);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'AWG', 2.0375);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'KRW', 1284.4479);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'NPR', 125.3919);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'JPY', 126.8069);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MNT', 2961.7500);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'AOA', 360.0810);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'PLN', 4.2873);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'GBP', 0.8652);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'SBD', 9.2529);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BYN', 2.3811);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'HUF', 322.0292);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BYR', 22186.2408);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BIF', 2069.8291);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MWK', 830.7333);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MGA', 4103.8928);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'XDR', 0.8142);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BZD', 2.2804);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BAM', 1.9558);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'EGP', 19.5590);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'MOP', 9.1397);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'NAD', 15.8025);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'NIO', 37.1473);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'PEN', 3.7260);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'NZD', 1.6740);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'WST', 2.9586);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'TMT', 3.9731);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'CLF', 0.0284);
INSERT INTO item_catalog.currency (code, rate) VALUES ( 'BRL', 4.3941);